import Head from 'next/head';
import { Box, Heading } from '@chakra-ui/react';
import FormContainer from '../components/FormContainer';
import { OverallContextProvider } from '../components/context/overallContext';

export default function Home() {
	return (
		<>
			<Head>
				<title>Multi-Form App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Box pt="8" px="28" h="100vh" pb="28">
				<Heading as="h1" fontSize="2rem" mb="4">
					Create Candidate Requisition
				</Heading>
				<OverallContextProvider>
					<FormContainer />
				</OverallContextProvider>
			</Box>
		</>
	);
}
